name: Run VKE Script

on:
  workflow_dispatch:
    inputs:
      isim_soyisim:
        description: "İsim ve Soyisim"
        required: true
        default: "Ahmet Kaya"
      boy:
        description: "Boy (metre cinsinden, ör: 1.75)"
        required: true
        default: 1.75
      kilo:
        description: "Kilo (kg)"
        required: true
        default: 70
  push:
    branches:
      - sonuclar

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Display inputs (Debug)
      run: |
        echo "isim_soyisim: ${{ github.event.inputs.isim_soyisim }}"
        echo "boy: ${{ github.event.inputs.boy }}"
        echo "kilo: ${{ github.event.inputs.kilo }}"

    - name: Create input_data.txt
      run: |
        echo "${{ github.event.inputs.isim_soyisim }}" > input_data.txt
        echo "${{ github.event.inputs.boy }}" >> input_data.txt
        echo "${{ github.event.inputs.kilo }}" >> input_data.txt
        cat input_data.txt  # Dosyanın içeriğini yazdır

    - name: Check for Invalid Data in input_data.txt
      run: |
        # Boy ve kilo değerlerini kontrol et (negatif olmamalı)
        boy=$(sed -n '2p' input_data.txt)
        kilo=$(sed -n '3p' input_data.txt)

        # Boy ve kilo negatif mi?
        if [[ "$boy" =~ ^- ]]; then
          echo "Hata: input_data.txt dosyasındaki boy negatif değer içeriyor!"
          exit 1  # İşlem başarısız olur
        fi

        if [[ "$kilo" =~ ^- ]]; then
          echo "Hata: input_data.txt dosyasındaki kilo negatif değer içeriyor!"
          exit 1  # İşlem başarısız olur
        fi

        # Değerler sayıya dönüşebiliyor mu?
        if ! [[ "$boy" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
          echo "Hata: input_data.txt dosyasındaki boy geçerli bir sayı değil!"
          exit 1
        fi

        if ! [[ "$kilo" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
          echo "Hata: input_data.txt dosyasındaki kilo geçerli bir sayı değil!"
          exit 1
        fi

        echo "Veri geçerli!"  # Eğer her şey doğruysa, veri geçerli!

    - name: Run VKE Script
      run: |
        python main.py
