name: Run VKE Script

on:
  workflow_dispatch:
    inputs:
      isim_soyisim:
        description: "İsim ve Soyisim"
        required: true
        default: "Örnek İsim"
      boy:
        description: "Boy (metre cinsinden, ör: 1.75)"
        required: true
        default: 1.75
      kilo:
        description: "Kilo (ör: 70)"
        required: true
        default: 70

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run VKE Script
      run: |
        echo "${{ github.event.inputs.isim_soyisim }}" > input_data.txt
        echo "${{ github.event.inputs.boy }}" >> input_data.txt
        echo "${{ github.event.inputs.kilo }}" >> input_data.txt
        python main.py