name: Run VKE Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Debug input_data.txt
      run: |
        echo "input_data.txt dosyasının içeriği (satır numarası ile):"
        cat -n input_data.txt

    - name: Check for Invalid Data in input_data.txt
      run: |
        boy_cm=$(sed -n '2p' input_data.txt | tr -d '[:space:]')
        kilo=$(sed -n '3p' input_data.txt | tr -d '[:space:]')

        if [ "$boy_cm" -lt 0 ]; then
          echo "Hata: Boy negatif bir değer!"
          exit 1
        fi

        if [ "$kilo" -lt 0 ]; then
          echo "Hata: Kilo negatif bir değer!"
          exit 1
        fi

        echo "Boy: '$boy_cm', Kilo: '$kilo'"

    - name: Run VKE Script
      run: |
        python main.py