name: Run VKE Script

on:
  workflow_dispatch:
    inputs:
      isim_soyisim:
        description: "İsim ve Soyisim"
        required: true
        default: "Ahmet Kaya"
      boy:
        description: "Boy (santimetre cinsinden, ör: 175)"
        required: true
        default: 175
      kilo:
        description: "Kilo (kg)"
        required: true
        default: 70
  push:
    branches:
      - sonuclar

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create input_data.txt
      run: |
        echo "isim_soyisim: ${{ github.event.inputs.isim_soyisim }}"
        echo "boy: ${{ github.event.inputs.boy }}"
        echo "kilo: ${{ github.event.inputs.kilo }}"

        echo "${{ github.event.inputs.isim_soyisim }}" > input_data.txt
        echo "${{ github.event.inputs.boy }}" >> input_data.txt
        echo "${{ github.event.inputs.kilo }}" >> input_data.txt
        echo "input_data.txt dosyasının içeriği:"
        cat -n input_data.txt  # Satır numaraları ile içeriği kontrol et

    - name: Normalize line endings (Windows/Newline cleanup)
      run: |
        sed -i 's/\r//' input_data.txt  # Windows tarzı satır sonlarını temizle
        echo "input_data.txt dosyasının içeriği (sonra):"
        cat -n input_data.txt  # İçeriği tekrar kontrol et

    - name: Check for Invalid Data in input_data.txt
      run: |
        # Boy ve Kilo değerlerini al, boşlukları temizle
        boy_cm=$(sed -n '2p' input_data.txt | tr -d '[:space:]')  # Boyu al ve boşlukları temizle
        kilo=$(sed -n '3p' input_data.txt | tr -d '[:space:]')    # Kilo değerini al ve boşlukları temizle

        # Debug: Boy ve Kilo değerlerini yazdır
        echo "Debug: Boy değeri: '$boy_cm', Kilo değeri: '$kilo'"

        # Boy ve Kilo boş mu?
        if [[ -z "$boy_cm" ]] || [[ -z "$kilo" ]]; then
          echo "Hata: Boy veya Kilo boş değer içeriyor!"
          exit 1
        fi

        # Debug: Değerler kontrol edilerek yazdırılır
        echo "Boy: '$boy_cm', Kilo: '$kilo'"

        # Negatif değer kontrolü (Sayısal karşılaştırma ile)
        if [ "$boy_cm" -lt 0 ]; then
          echo "Hata: Boy negatif bir değer!"
          exit 1
        fi

        if [ "$kilo" -lt 0 ]; then
          echo "Hata: Kilo negatif bir değer!"
          exit 1
        fi

        echo "Değerler geçerli. İşleme devam ediliyor."

    - name: Run VKE Script
      run: |
        python main.py
