name: Run VKE Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-vke-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Python sürümünüzü burada belirtebilirsiniz.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run VKE Script
      run: |
        python main.py