name: Run VKE Script

on:
  workflow_dispatch:
    inputs:
      isim_soyisim:
        description: "İsim ve Soyisim"
        required: true
        default: "Ahmet Kaya"
      boy:
        description: "Boy (santimetre cinsinden, ör: 175)"
        required: true
        default: 175
      kilo:
        description: "Kilo (kg)"
        required: true
        default: 70

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create input_data.txt
      run: |
        echo "${{ github.event.inputs.isim_soyisim }}" > input_data.txt
        echo "${{ github.event.inputs.boy }}" >> input_data.txt
        echo "${{ github.event.inputs.kilo }}" >> input_data.txt

    - name: Debug input_data.txt
      run: |
        echo "input_data.txt dosyasının içeriği:"
        cat input_data.txt

    - name: Check for Invalid Data in input_data.txt
      run: |
        boy_cm=$(sed -n '2p' input_data.txt)  # Boyu al
        kilo=$(sed -n '3p' input_data.txt)    # Kilo değerini al

        if [[ $boy_cm =~ ^- ]] || [[ $kilo =~ ^- ]]; then
          echo "Hata: Negatif değerler bulundu!"
          exit 1
        fi

        echo "Değerler geçerli. İşleme devam ediliyor."

    - name: Run VKE Script
      run: |
        python main.py
