name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Repository'yi klonlama
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python'u kurma
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Hedef Python sürümünü belirtin

      # Bağımlılıkları yükleme (requirements.txt varsa)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Kodun çalıştığını doğrulama
      - name: Run script
        run: |
          python your_script_name.py < input_data.txt

      # Çıktıyı kontrol etme (isteğe bağlı)
      - name: Verify results
        run: |
          ls -la